### PR TITLE
Change web_modules dir structure

### PR DESCRIPTION
**Pull request by mxstbr**
See https://github.com/postcss/postcss.com/issues/13#issuecomment-170243565

### CODE REVIEW

**Comment by mxstbr** [comment]
Can I approve my own PR?

LGTM

**Comment by marcustisater** [comment]
LGTM

**Comment by mxstbr** [comment]
Apparently I can, nice!

**Comment by marcustisater** [comment]
Yeah, I guess that works :+1:

**Comment by MoOx** [comment]
:+1:

**Pull request merged**
