### PR TITLE
Dir structure

### PR DESCRIPTION
**Pull request by mxstbr**
I didn't like the naming of the folder and the files, so I changed the folder name to utils and put all the exports into the same file.

This has the benefit that new developers won't be tempted to look at the unnecessary "routes.js" file, which you never need to change. Better separation of concerns for beginners.

I also renamed "routes" to "RouteHandler", because that's what it really does. I have to do 

```JS
const routes = RouteHandler
```

in the scripts because Statinamic requires a variable called "routes". This is kind of ugly, but it works, (nobody will need to touch that ever again), and it's much clearer for beginners.

Thoughts @MoOx?

> Note: I did this change without the merged directory structure changes, so I will have to manually merge.

### CODE REVIEW

**Comment by mxstbr** [comment]
LGTM

**Comment by MoOx** [comment]
That's a good discussion.
I found this was a good idea before I open the "huge" and complicated file (utils/index).
Now if a newbie wants to define and add a new page layout he will have to check this "huge" file (not that huge but still).
By being "long" (when you have to use `/** ... */` comment, it's a sign), this makes it more complicated to understand what is related to why.
So I am not a fan.

**Comment by mxstbr** [comment]
What about factoring out the layouts as `layouts.js` but having the rest in the `index.js`? The seperate `routes.js` and `store.js` don't really help, because what do you use them for? Nothing really, they're mostly boilerplate and probably won't change.

**Comment by MoOx** [comment]
That's a good idea.

**Comment by MoOx** [comment]
I might give more detail about that in statinamic advanced doc.

**Comment by mxstbr** [comment]
@MoOx done, review please!

**Comment by mxstbr** [comment]
Forgot to lint, don't merge yet please, need to change the code style in certain places

**Comment by MoOx** [comment]
lgtm

**Pull request merged**
