### PR TITLE
Add LGTM.co

### LINKED ISSUE #34: Add https://lgtm.co
> Pull Requests are reviewed by members of the team specified in the MAINTAINERS file in your repository and cannot be merged until all approvals are received.

> Approvers comment on the issue with LGTM, looks good to me, indicating their approval to merge the changeset.

This looks very useful for this project, this means without approval of the core maintainers no PR can be merged.

@ai @marcustisater do you want to be in the MAINTAINERS file? You'd have to comment each and every PR then with `LGTM` though.

### PR DESCRIPTION
**Pull request by mxstbr**
Closes #34

Don't merge just yet please, we need [this](https://github.com/postcss/postcss.com/issues/34#issuecomment-169762741) to happen first @ai 

You can approve by commenting one of these three:

1. LGTM (`LGTM`)
2. :+1: (`:+1:`)
3. :shipit: (`:shipit:`)

### CODE REVIEW

**Comment by mxstbr** [comment]
I've currently only added the four that commented #34, if @jonathantneal and @stephenway want to be added please lmk

**Comment by mxstbr** [comment]
LGTM

**Comment by MoOx** [comment]
Remember to delete branch when you merge a PR, otherwise you will quickly have too many ;)

**Comment by mxstbr** [comment]
Ah yeah my bad, thanks!

**Pull request merged**
