### PR TITLE
Added CC-BY-4.0 License for docs [touch:19]

### PR DESCRIPTION
**Pull request by marcustisater**
Can you approve the license? This should be used for documentation/content.  

cc @ai

### CODE REVIEW

**Comment by ai** [comment]
I hate that Creative Commons licenses do not write a its type in document title. Maybe we should rename it to `CC-BY-Licence`?

**Comment by marcustisater** [comment]
It says `Creative Commons Attribution 4.0 International Public License` on top of the file.

**Comment by marcustisater** [comment]
Ok, we can rename it as well, that makes sense too.

**Comment by ai** [comment]
But `Creative Commons Attribution 4.0 International Public License` does not clear difference between CC-BY, CC-BY-SA, CC-BY-NC.

**Comment by marcustisater** [comment]
Yup, that's correct. I forgot that.

**Comment by marcustisater** [comment]
Alright, merged into master. Thanks for clearing this out @ai

**Pull request merged**
